spring.application.name=WorkOrderCentral

spring.profiles.include=pg


license.key=ENC(k3l4d+mC0jG8B0YY8UuFXrgg88CnzSvLE3qd6eRSrYt8oL7Z6R6ut7rCOQ+kdWEnrtVA0XXFP7XIKSws5LkaMhX7+gXMPAAHoVTb6/862X9+d2kHgPcO5EvxTSsSlXCz0KrUzxp9kKRj4xsbFvT/mae99Ufi7pS9vd+kbEeWulc=)

