title=Radni nalog
workOrder=Radni nalog
purchaseOrder=Broj narudžbenice
buyerId=ID naručioca / kupca
product=Stavka proizvoda
productQuantity=Naručena količina
stockAssignedQuantity=Količina dodeljena iz magacina
dueDate=Rok
startDate=Datum početka
endDate=Datum završetka
comment=Komentar
materialsTitle=Potrebni materijali
materialCode=Šifra materijala
materialName=Naziv materijala
quantity=Količina
noMaterials=Za ovaj proizvod nije definisan sastav materijala.
technologyTitle=Tehnologija
cycleTime=Vreme ciklusa
norm100=Norma 100
piecesPerMaterial=Komada po materijalu
tools=Alati
toolWorkingTime=Vreme rada
noTechnology=Za ovaj proizvod nije definisana tehnologija.
machineTitle=Dodeljena mašina
machineName=Mašina
engagementFrom=Od
engagementTo=Do
noMachine=Nema dodeljene mašine.
